# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule:
    - cron: "0 */24 * * *" 
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.posts.full.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: http://blog.mankiratsingh.com/index.xml
          plugin_rss_limit: 4
